ACCESS-NRI/build-ci

.github/workflows/build-and-push-image-build.yml

For this to work, one needs to trigger the creation of the base image, so that it uses the latest version of ACCESS-NRI/spack_packages.

Add ACCESS-OM3 to list of packages to build

---

.github/workflows/build-and-push-image-base-spack.yml
containers/Dockerfile.base-spack

This PR adds in a required input to the build-and-publish-image-base-spack GitHub Action that specifies either a commit hash, tag or branch name for ACCESS-NRI/spack_packages. This defaults to `main`. 
Should close #6 !

#6 ACCESS-NRI/spack_packages Git Version Option

---

.github/workflows/build-and-push-image-build.yml
.github/workflows/build-package.yml
README.md

#6  was re-opened to accommodate some more required features (see https://github.com/ACCESS-NRI/build-ci/issues/6#issuecomment-1633570952) - namely, the ability to pick a spack_packages version from the model version of the workflow. 
This would mean that the built package would be of the form `build-<model>-<compiler><compiler version>-<spack_packages version>:latest`. For example: `built-oasis3-mct-intel2021.1.2-main`. 
Should close #6

Fix to spack_packages version option

---

.github/workflows/build-and-push-image-build.yml

Although issues with dependencies/variants going to slack 0.20.1, this is just adding CICE5 to the base image.

13 add cice5

---

.github/workflows/notified-of-spack-packages-update.yml

The build was failing with
> he workflow is not valid. .github/workflows/notified-of-spack-packages-update.yml (Line: 16, Col: 3): Error calling workflow 'access-nri/workflows/.github/workflows/build-and-push-image-base-spack.yml@main'. The nested job 'build-and-push-image' is requesting 'packages: write', but is only allowed 'packages: read'.
Granting explicit permissions should fix this.

Added appropriate permissions for base-spack workflow call

---

.github/workflows/notified-of-spack-packages-update.yml
util/matrix_generation.py
util/test_matrix_generation.py

Testing continues! I am now using my own fork of build-ci to allow for testing without needing to use ACCESS_NRIs own workflows. 
Updates to the workflows reusable workflows, as well as changes to the matrix_generation python script, are in the PR.

matrix_generation and workflow fixes

---

.github/workflows/build-and-push-image-base-spack.yml
.github/workflows/notified-of-spack-packages-update.yml

Instead of inheriting secrets across reusable workflows (namely, build-and-push-image-base-spack.yml), just pass the secrets directly to build-and-push-image.yml.

Build spack-base directly with build-and-push-image

---

containers/Dockerfile.base-spack

Small optimization - the spack environment is already set up as an entrypoint to the Dockerfile.
Should close #51 !

Removed setting of spack PATH as it is already done later

---

.github/workflows/build-and-push-image.yml

Github Actions natively supports caching between jobs, but we haven't been able to use it for docker images yet. This PR adds the ability to cache the images between builds. 
Should close #54 !

Added Docker image caching in Github Actions Workflow

---

containers/Dockerfile.base-os

```
Group: Development Tools
Description: A basic development environment.
Mandatory Packages:
autoconf
automake
binutils
bison
flex
gcc
gcc-c++
gdb
glibc-devel
libtool
make
pkgconf
pkgconf-m4
pkgconf-pkg-config
redhat-rpm-config
rpm-build
rpm-sign
strace
Default Packages:
asciidoc
byacc
ctags
diffstat
elfutils-libelf-devel
git
intltool
jna
ltrace
patchutils
perl-Fedora-VSP
perl-Sys-Syslog
perl-generators
pesign
source-highlight
systemtap
valgrind
valgrind-devel
Optional Packages:
cmake
expect
rpmdevtools
rpmlint
```

Do not install group "Development Tools", select individual packages

---

containers/Dockerfile.base-os
containers/Dockerfile.base-spack

The dev Dockerfile doesn't need boto3.

Move boto3 install out of Dockerfile.base-os and into Dockerfile.base-spack

---

.github/workflows/build-and-push-image-build.yml
.github/workflows/dependency-image-pipeline.yml
containers/Dockerfile.access-om2
containers/Dockerfile.access-om3
containers/Dockerfile.base-spack
containers/setup-spack-envs.sh

Pushing the compiler down into base-spack as it is not updated as frequently in the pipeline and can therefore help compilation times. This PR changes the workflows somewhat, in which the matrix is created relatively early in the pipeline, and is fed into the new workflow (dependency-image-pipeline.yml)
Should close #50 !

Compiler in base-spack

---

.github/workflows/dependency-image-pipeline.yml

'@'s aren't allowed in package names and would therefore fail to push. This PR fixes that. 
Should close #65 !

Removed '@'s in package names

---

.github/workflows/build-and-push-image-build.yml

The nested workflow is requiring `packages:write` but by default only gets `packages:read` as noted in the logs here: https://github.com/ACCESS-NRI/build-ci/actions/runs/5957828644/workflow
This PR gives the dependency-image-pipeline `contents:read` and `packages:write`.

gave image pipeline the appropriate packages:write permissions

---

.github/workflows/build-and-push-image-build.yml
.github/workflows/dependency-image-pipeline.yml

Workflow failed to parse the matrix strategy because it was being interpreted as a string rather than a JSON object. Logs here: https://github.com/ACCESS-NRI/build-ci/actions/runs/5957933943 
This PR parses the string from `generate-matrix` as a JSON object.

Parsed matrix as json rather than as a string

---

.github/workflows/dependency-image-pipeline.yml

The old conditional was essentially: If the image doesn't exist, skip the image-creation job. It now appropriately checks if the manifest doesn't exist, then the next job (which creates it) will fire.

Rearranged some image-check conditionals

---

.github/workflows/dependency-image-pipeline.yml

The `docker manifest inspect` command doesn't write to standard out in the expected way. So, instead of comparing the output of the command, we shall compare the exit code of the command (where nonzero means the image doesn't exist, and zero means it does).  
Should close #80 !

Replace output comparison with exit code comparison

---

.github/workflows/build-and-push-image-build.yml
.github/workflows/build-and-push-image.yml
.github/workflows/dependency-image-pipeline.yml

Modified the matrix strategy from a all-at-once 'compiler x model' strategy to a 'first compiler matrix (for base-spack) then model matrix'. This means that multiple 'base-spack' images will not be built in parallel. 
Should close #83 !

Modified matrix strategy, pushing model matrix down later in the pipeline

---

containers/Dockerfile.base-spack
containers/setup-spack-envs.sh

So spack uses the existing compiler target when in an environment rather than choosing for itself.
Should go some way to completing #86

Added `target` to all other `spack install`s

---

.github/workflows/build-package.yml
containers/models.json

Most of the information in the model CI can be inferred from the model repository itself, or the `build-ci` repo.  For example: https://github.com/ACCESS-NRI/MOM5/blob/master/.github/workflows/test-build.yml contains information on the package name and compilers, which can be determined from the repository name and `build-ci/containers/compilers.json` respectively. 
This PR removes the inputs from the build-package reusable workflow and infers them in a `setup` job instead, which will allow all models to use the exact same workflow file. If they can all use the same workflow file, then we can create a starter workflow for any future models as well (provided there is a `.github` repo at the root of the organisation that specifies one).
References #91 (and will close it once all models …

Make build-package workflow generic

---

.github/workflows/build-package.yml

Failed to build image name because the output of jq was is in quotes, and image used the upper case MOM5. 
This PR make jq use the `-cr` flag (compressed and raw output) and also makes the setup-build-ci need setup-model for the lowercase model
References #91

jq uses raw output and uses the lower-case repo name

---

README.md
containers/Dockerfile.base-spack
containers/compilers.json
util/build_dockerfile.build.sh

* Compiler version set to 2021.2.0 because Gadi /apps does not have 2021.1.2.
* Explicit bootstrap not required.
* Clone and add spack_packages last in the base-spack target.
```
$ docker build -f Dockerfile.base-spack -t spack-dev:20230831.1 --target=dev  .
[+] Building 2404.2s (14/14) FINISHED                                           
=> [internal] load build definition from Dockerfile.base-spack            0.0s
=> => transferring dockerfile: 4.78kB                                     0.0s
=> [internal] load .dockerignore                                          0.0s
=> => transferring context: 2B                                            0.0s
=> [internal] load metadata for docker.io/library/rockylinux:8.8          0.0s
=> [base-os 1/2] FROM docker.io/library/rockylinux:8.8 …
```

base-spack: install the compiler earlier

---

containers/Dockerfile.access-om2
containers/Dockerfile.access-om3
containers/Dockerfile.base-spack
containers/setup-spack-envs.sh

Instead of environment variables looking like `$THIS` they look like `${THIS}` now. Also changed sub-command expansion from backticks to `$(...)` as that is standard.
Should close #89

Standardized env and arg vars to use curly braces

---

.github/workflows/json-lint.yml
containers/compilers.schema.json
containers/models.schema.json

Added `*.schema.json` files for validation CI. Can be done on CLI with (for example) `jsonchema -i containers/compilers.json containers/compilers.schema.json`. 
Added build-ci CI (how meta!) for json validation. 
Should close #63 !

JSON Schema and JSON Validation CI

---

.github/workflows/model-1-build.yml

For a full understanding (or for a long rambling rant) of the context of this PR, see the linked issue  🤪
In this PR:
* we add a `git fetch --unshallow` before our `git describe --tags --abbrev=0` command so we have the full, unfragmented history of `main` and fetching the last tag works correctly. 
* Updated some of the names to be shorter. 
* We now use `--abbrev=0` so we don't get all the metadata at the end of the tag name
Should close #102 !

Get full history of the branch so `git describe --tags ...` works correctly

---

.github/documentation.md
README-DEV.md
README.md

With all the changes to the CI pipeline, the documentation has gone out of date. In this PR:
* Update of `README.md` to contain a summarised Overview and Usages 
* Creation of a `README-DEV.md` that contains a pipeline run through that is more useful to developers
Should close #22 !

Readme and documentation updates

---

.github/workflows/json-1-validate.yml
.github/workflows/validate-json.yml
README-DEV.md
README.md

Makes the JSON Validate workflow usable by:
* creating a new reusable workflow that has a `workflow_call` trigger (called `validate-json.yml`)
* Remove references to directories (specifically `containers`) and referring to `workflow_call.inputs.src`
* Expand all the flags of commands from their short version to the long version for more understandability (for example, `-R` to `--raw-input` for the call to `jq`)
* Simplifying the actual call in `json-1-validate.yml` to simply call the newly created workflow above. 
Closes #104 !

Make JSON validation workflow reusable

---

containers/Dockerfile.base-spack

* The latest cmake version in Gadi's /apps is 3.24.2

Dockerfile.base-spack: explicitly install cmake 3.24.2

---

containers/Dockerfile.base-spack

Cloning a release branch enables important bug fixes, via minor releases, to be automatically received without having to update this Dockerfile after each minor release creates a new tag.

Dockerfile.base-spack: clone a spack release branch instead of a tag

---

containers/Dockerfile.base-spack

* No need to do `spack repo add` because it's already in spack_config

Dockerfile.base-spack: use versioned target directories of spack_config

---

.github/workflows/dep-image-2-build.yml

In this PR:
* Containing multiline gpg file secrets in quotes, as noted in https://docs.docker.com/build/ci/github-actions/secrets/
Closes #130﻿

Proper multiline secret containment

---

.github/workflows/dep-image-2-build.yml

During the reconfiguration of `build-ci`, a regression was introduced that meant the `models.json` was being read without being checked out, leading to a dependency image that didn't actually have any dependencies in it.

Adding checking out of `models.json` during dependency image creation

---

containers/Dockerfile.dependency

The current dependency image doesn't have the recommended spack entrypoint, which would lead to any uses of the image needing to run `. $SPACK/share/spack/setup-env.sh` before any other commands are run.

Dockerfile.dependency: added spack entrypoint to dependency image

---

.github/workflows/model-1-build.yml

Due to GitHub Actions not honoring Dockers `ENTRYPOINT` command, we need to activate spack using the provided `$SPACK/share/spack/setup-env.sh` script.

Added step in Model Build workflow to activate spack

---

.github/workflows/model-1-build.yml
containers/Dockerfile.dependency

In this PR:
* `Dockerfile.dependency`: 
* Removed garbage collection as it was deleting packages that would be reinstalled later
* Removed `ENTRYPOINT` command and added a comment noting why it isn't there (see: https://stackoverflow.com/questions/66358482/github-actions-ignores-overrides-docker-containers-entrypoint)
* `model-1-build.yml`: 
* Added setup of environment and compilers when running the container
* Added volumes that store various environment files that are uploaded as artifacts
* Removed `tmate` remote debugging because the logs should be sufficient 
* Cleaned up some of the code and logic
Closes #137

Dependency Image Spack fix

---

containers/Dockerfile.base-spack

The CMake version will now come from the spack-config repository. See https://github.com/ACCESS-NRI/spack-config/pull/21 .

Dockerfile.base-spack: remove cmake version from dev target

---

containers/Dockerfile.base-spack

The MPI name and version should not be hardcoded in the dev target.

Dockerfile.base-spack: add new args MPI_NAME and MPI_VERSION

---

containers/Dockerfile.base-spack

From v0.20 to v0.21, Spack appears to have changed the permitted syntax of compiler and arch arguments during a spack install. See https://github.com/ACCESS-NRI/build-ci/issues/139

Dockerfile.base-spack: add arch arg after each compiler arg

---

containers/Dockerfile.base-spack

Perl is installed implicitly as a dependency in target base-os. Make it explicit now that we do not build it via Spack.
See https://github.com/ACCESS-NRI/spack-config/pull/22

Dockerfile.base-spack: explicitly install perl in base-os

---

containers/Dockerfile.base-spack

While attemping to test a new version of Spack via the Docker image, I noticed that $SPACK_ROOT/etc/spack didn't contain symlinks to spack-config config files. This change will generate an ENOENT error, if the directory for a particular Spack version does not exist.

Dockerfile.base-spack: check if $SPACK_CONFIG_DIR exists

---

containers/Dockerfile.base-spack

* Gadi has been upgraded to Rocky Linux 8.9.

Dockerfile.base-spack: upgrade from Rocky Linux 8.8 to 8.9

---

config/compilers.json

In this PR: 
* Added entry in `compilers` table for `intel@2021.4.0` as `intel@2021.2.0` can't be downloaded at the moment
Closes #148

Added entry for `intel@2021.4.0` in `config/compilers.json` 

---

config/compilers.json

See https://github.com/ACCESS-NRI/build-ci/actions/runs/8291385383/job/22690995420#step:4:3320
Due to this compiler failing to be fetched from intels sources, we have removed it and replaced it with `intel@2021.4.0`.

compilers.json: Removed intel@2021.4.0

---

containers/Dockerfile.base-spack

* SPACK_GIT_URL defaults to ACCESS-NRI's Spack fork. This fork contains a backport of commit
"Update Intel download URLs (#43286)"

Dockerfile.base-spack: add new ARG SPACK_GIT_URL

---

containers/Dockerfile.base-spack
containers/Dockerfile.dependency
containers/setup-spack-envs.sh

* The newer Intel oneAPI compiler packages contain a legacy Fortran compiler and a modern LLVM Fortran compiler. The compiler package version does not correspond with the legacy Fortran compiler version.

Dockerfile: decouple compiler package version and compiler version

---

.github/workflows/model-1-build.yml

This PR came about due to this https://github.com/CABLE-LSM/CABLE/pull/271 - specifically https://github.com/CABLE-LSM/CABLE/actions/runs/8794039008/job/24132843568?pr=271#step:4:10 - we had renamed a variable in the Dockerfile (PR here: https://github.com/ACCESS-NRI/build-ci/pull/155) but didn't do it in the CI. 
In this PR:
* model-1-build.yml: Replaced `$SPACK_ENV_ARCH` with `$ENV_SPACK_ARCH`

CI/CD: Updated ENV_SPACK_ARCH Variable

---

config/models.json

Addition of components for `access-esm1.5`. For now, this will only be the public components as the docker images are freely pullable. Might have to turn the packages into `internal` packages. 
In this PR:
* models.json: Added public access-esm1.5 package components

`models.json` Entry for ACCESS-ESM1.5

---

config/compilers.json

In this PR:
* Updating compiler to 2021.4.0 from 2021.2.0 to further https://github.com/CABLE-LSM/CABLE/pull/271

Default compiler update from `intel@2021.2.0` to `intel@2021.4.0`

---

.github/workflows/dep-image-1-start.yml
.github/workflows/dep-image-2-build.yml
.github/workflows/model-1-build.yml
config/compilers.json
config/compilers.schema.json

Bringing the `build-ci` workflow in line with the improvements to the Docker Image. 
In this PR:
* Workflow now uses the `spack-config` repository
* Workflow now uses a new field in `compilers.json` - the `package-version` of the compiler, so it doesn't default to `2021.2.0` in the repository. 
Closes #161

Dockerfile additions to workflow

---

.github/workflows/model-1-build.yml

Continues fixes implemented in https://github.com/ACCESS-NRI/build-ci/pull/162
In this PR:
* Replaces field names for `matrix.compiler.*` to be the ones specified in `config/compilers.json`
* In case of failure, force concretization uses `spack-enable.bash`

model-1-build.yml: Replaced matrix job fields, uses spack-enable.bash

---

containers/Dockerfile.dependency

The `0.20` version of the image contained a (deprecated) `-m` flag in the `spack buildcache create` command (see https://spack.readthedocs.io/en/v0.20.3/command_index.html#spack-buildcache-push).
In the later version (https://spack.readthedocs.io/en/latest/command_index.html#spack-buildcache-push, updated in https://github.com/ACCESS-NRI/build-ci/pull/166), the `-m` flag is removed, instead taking mirror as a positional argument. This PR uses the mirror as a positional arg. 
In this PR:
* Removed the -m flag as `mirror` is now positional

Update `spack buildcache` command for `spack >=0.21`

---

containers/Dockerfile.dependency

See https://github.com/ACCESS-NRI/build-ci/actions/runs/9605847929/job/26494707679#step:4:9413
The [new](https://github.com/ACCESS-NRI/build-ci/pull/167) `spack buildcache push` command is rejecting pushes of packages that have the same name. In this PR, we remove the `jq` that gives all the packages that we want to push - by default it will push all the packages in the environment (with hashes appended). 
In this PR:
* Update the `spack buildcache push` command to push packages of a specific hash

Dependency Images not building due to `spack buildcache push` clashing packages

---

containers/setup-spack-envs.sh

See failed run: https://github.com/ACCESS-NRI/build-ci/actions/runs/9608705872/job/26501970133#step:4:8470
Using `spack buildcache push` without a list of `specs` assumes that you want to push all of them. However, if not all of them are installed (as is the case in our dependency image, which `spack install --only dependencies ...`) it fails. So leaving the `jq` in was needed. 
To solve the original issue in https://github.com/ACCESS-NRI/build-ci/pull/168, we now get both the name of the package, and the hash, so we can push up different versions of the same package. 
We also remove the `--allow-root` flag as it is assumed in `0.21`, and removed in `0.22`.
In this PR:
* setup-spack-envs.sh: Removed --allow-root (assumed in 0.21), added back hash-delineated jq

Add back `jq` to `spack buildcache push`

---

.github/workflows/model-1-build.yml

In this PR:
- Update `env.SPACK_YAML_LOCATION` to `$SPACK_ROOT/../environments` due to ACCESS-NRI/spack-config@8a0425e595218e43b340587e8c04fd34f113bddb
Closes #178

Update `env.SPACK_YAML_LOCATION` to reference new `spack-config` Update

---

.github/workflows/model-1-build.yml

In this PR:
* Add new inputs to the model build stage that allow customizable variants/RHS version sections. This is left to the caller to implement.

Support non-default RHS versions, variants

---

containers/Dockerfile.base-spack
containers/README.md

* SUSE Linux Enterprise Server 15 SP5 is installed on Setonix

Dockerfile.base-spack: add option to build with opensuse/leap:15.5.

---

containers/Dockerfile.base-spack

* This ensures that cmake depends on the gmake built with the compiler we selected.

Dockerfile.base-spack: build gmake before cmake

---

config/compilers.json

References #205
There has been an issue with `build-ci` in which components are failing to be built.
In this PR:
* We update the compiler package version to `2023.2.4`, and the compiler version to `2021.10.0`

Updated compiler to 2021.10.0

---

.github/actions/git-checkout-updated-ref/README.md
.github/actions/git-checkout-updated-ref/action.yml
.github/workflows/ci.yml
util/generate_buildcache_keys.sh

See https://github.com/ACCESS-NRI/MOM5/actions/runs/15695675683/job/44220448187#step:2:143
When we use the default values for `*-ref` inputs, we skip the relevant repo update steps. However, this is how we get the SHAs that are outputted, leading to no SHAs outputted for repos that use defaults. 
In this PR, we no longer skip the update action steps, and output the SHA (updated or not) in that action. We also add a new output `updated` that allows a later relinking step (between `spack` and `spack-config`) only go ahead if those repos were updated. 
In this PR:
- **Update git-checkout-updated-ref to note whether the ref was actually updated**
- **Always attempt to update refs, and only relink config to spack if actually updated**
- **Delete util folder as we don't need buildcache keys**
- …

Output SHAs even when refs aren't updated

---

containers/Dockerfile
containers/upstream/dev/packages.spack.yaml
containers/upstream/prod/packages.spack.yaml

CABLE-LSM/CABLE is using a prototype GitHub-hosted CI 2.0 without a buildcache at the moment. This means that builds are actually slower than the original, everything-except-the-dependent way. 
To get it as close as we can, we should include relevant versions of `netcdf-c` and `netcdf-fortran` in the upstream image. 
Furthermore, since we can't share data between service containers in GitHub-hosted mode, we have elected to just run the upstream container as the runner container. This means that the upstream image requires tmate to be installed. 
- **Add tmate to both runner and upstream images**
- **Add netcdf-c@4.9.2 and netcdf-fortran@4.5.2 to upstream packages**

Update Upstream Image Packages and Dependencies

---

.github/workflows/README.md
.github/workflows/ci-github-hosted.yml
.github/workflows/ci.yml

It was noted while testing out the GitHub-hosted variant of the CI that it is important that the user can pin a particular version of the conatiner image, since the GitHub variant can't yet make use of the buildcache, so must use the packages installed on the image for quick installs. If a user pins a particular package hash in the manifest, via `/HASH`, this hash could change between image versions. 
Furthermore, it was noted that it is difficult to aggregate data relating to multiple instances of a matrix invocation of the CI. A similar solution to this problem was found in `build-cd`, which we reuse here - uploading an artifact per instance of the job with a common prefix, downloading all artifacts, and then processing them.
- **Added new optional input container-image-version for …

Allow specification of container image version, allow aggregation of matrix instance outputs

---

containers/upstream/dev/compilers.spack.yaml
containers/upstream/dev/packages.spack.yaml
containers/upstream/prod/compilers.spack.yaml
containers/upstream/prod/packages.spack.yaml

The current oneapi compiler doesn't actually work well, so it's been updated. `gcc@8.5.0` is very old and shouldn't be what we test against. 
> [!NOTE]
> A new version of the image needs to be pushed before this is merged, and updated in the upstream.

Replace intel@2025.0.4 with intel@2025.2.0, add gcc#13.2.0

---

.github/workflows/README.md
README.md
model-component-ci-templates/README.md
model-component-ci-templates/build-ci/data/standard.json
model-component-ci-templates/build-ci/manifests/spack.yaml.j2
model-component-ci-templates/workflows/basic-ci.yml
model-component-ci-templates/workflows/matrix-ci.yml

Closes #226
Rather than rewriting the same manifests and CI for every MCR, add some basic templates that can be used out of the box by MCRs. 
Note that these are basic examples and more complex CI should be created for MCRs as required by use case. 
- **Add basic template for MCRs for single and matrix invocations**
- **Update README to note templates, and the existence of `ci-github-hosted.yml`**

Build CI Templates
